-- 1트
-- SELECT TO_CHAR(N.SALES_DATE, 'YYYY-MM-DD') SALES_DATE, 
--        N.PRODUCT_ID, NVL(N.USER_ID, NULL) USER_ID, N.SALES_AMOUNT
-- FROM ONLINE_SALE N, OFFLINE_SALE F
-- WHERE N.PRODUCT_ID = F.PRODUCT_ID AND
--       TO_CHAR(N.SALES_DATE, 'YYYY-MM') = '2022-03'
-- ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;

-- 2트
SELECT TO_CHAR(SALES_DATE, 'YYYY-MM-DD') SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM(SELECT ONLINE_SALE_ID, USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE
     FROM ONLINE_SALE
     UNION ALL
     SELECT OFFLINE_SALE_ID, NULL AS USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE
     FROM OFFLINE_SALE)
WHERE TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-03'
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;
