-- 코드를 작성해주세요
SELECT count(*) 'FISH_COUNT', ni.FISH_NAME
FROM FISH_INFO i
JOIN FISH_NAME_INFO ni ON i.FISH_TYPE = ni.FISH_TYPE
# WHERE i.FISH_TYPE = ni.FISH_TYPE
GROUP BY ni.FISH_NAME
ORDER BY FISH_COUNT desc;