-- 코드를 입력하세요
/* SELECT * FROM BOOK; */
SELECT BOOK_ID, to_char(PUBLISHED_DATE, 'YYYY-mm-dd') PUBLISHED_DATE
FROM BOOK 
WHERE to_char(PUBLISHED_DATE, 'YYYY') = '2021' AND CATEGORY='인문'
    ORDER BY PUBLISHED_DATE ASC;