-- 코드를 입력하세요

/*
ORDER BY 기본값: ASC 오름차순 
TO_CHAR(타입값,'날짜포맷') : 날짜타입의 데이터를 '날짜포맷'에 따라 문자열로 변환 
TO_DATE('문자열','날짜포맷'): '날짜포맷'에 맞춘 날짜문자열을 날짜타입값으로 변환 
*/

SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, TO_CHAR(R.CREATED_DATE, 'YYYY-MM-DD') "CREATED_DATE"
FROM USED_GOODS_BOARD B, USED_GOODS_REPLY R
WHERE B.BOARD_ID = R.BOARD_ID
      AND B.CREATED_DATE >= TO_DATE('2022-10-01', 'YYYY-MM-DD')
      AND B.CREATED_DATE <= TO_DATE('2022-10-31', 'YYYY-MM-DD')
      ORDER BY R.CREATED_DATE ASC, B.TITLE ASC;
      

