SELECT CATEGORY, SUM(SALES)
FROM BOOK b, BOOK_SALES bs
WHERE b.BOOK_ID = bs.BOOK_ID AND
    TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-01'
GROUP BY CATEGORY
ORDER BY CATEGORY

-- SELECT SALES_DATE
-- FROM BOOK b, BOOK_SALES bs
-- WHERE b.BOOK_ID = bs.BOOK_ID AND
--     TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-01'
